## contants in Tensorflow
`Syntax: constant(value, dtype=None, shape=None, name='Const', verify_shape=False)`

In [1]:
import tensorflow as tf

In [3]:
z = tf.constant(5.2,name='x',dtype=tf.float32)
z

<tf.Tensor: shape=(), dtype=float32, numpy=5.2>

## Variables in Tensorflow

In [5]:
v = tf.Variable(tf.ones([2,3]),dtype=tf.float32)
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [6]:
print(('Your Tensorflow version: {0}').format(tf.__version__))

Your Tensorflow version: 2.7.0


In [8]:
# Create a constant Tensor A
A = tf.constant([[4,3],[6,1]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1]])>

In [10]:
# Create a variable Tesnor V
V = tf.Variable([[3,1],[5,2]])
V
B = tf.constant([[7,8],[4,5]])
B

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 8],
       [4, 5]])>

In [12]:
# Concatenate Columns
AB_concatenated = tf.concat(values=[A,B],axis=1)
AB_concatenated

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 7, 8],
       [6, 1, 4, 5]])>

In [13]:
# Concatenate Rows
AB_concatenated = tf.concat(values=[A,B],axis=0)
AB_concatenated

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1],
       [7, 8],
       [4, 5]])>

In [18]:
tensor = tf.random.uniform(shape=[3,4],dtype=tf.float32)
tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.00210333, 0.20462668, 0.60315263, 0.15976286],
       [0.6569972 , 0.35406756, 0.99279535, 0.96573234],
       [0.43963385, 0.8092699 , 0.28234518, 0.8718562 ]], dtype=float32)>

In [19]:
# reshape
reshaped_tensor = tf.reshape(tensor=tensor,shape=[4,3])
reshaped_tensor

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.00210333, 0.20462668, 0.60315263],
       [0.15976286, 0.6569972 , 0.35406756],
       [0.99279535, 0.96573234, 0.43963385],
       [0.8092699 , 0.28234518, 0.8718562 ]], dtype=float32)>

In [23]:
# Typecast a tensor
tensor = tf.constant([[4.6,4.2],
                      [7.5,3.6],
                      [2.7,9.4],
                      [6.7,8.3]],
                     dtype=tf.float32)
tensor_as_int = tf.cast(tensor,tf.int32)
print(tensor)
tensor_as_int

tf.Tensor(
[[4.6 4.2]
 [7.5 3.6]
 [2.7 9.4]
 [6.7 8.3]], shape=(4, 2), dtype=float32)


<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 4],
       [7, 3],
       [2, 9],
       [6, 8]])>

In [24]:
# transpose
a = tf.transpose(tensor_as_int)
a

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 7, 2, 6],
       [4, 3, 9, 8]])>

In [26]:
# Matrix multiplication of tensors
A = tf.constant([[5,8],
                 [3,9]])
v = tf.constant([[4],[2]])
Av = tf.matmul(A,v)
Av

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[36],
       [30]])>

In [27]:
# identity matrix
A_identity = tf.eye(num_rows=3,num_columns=3,dtype=tf.float32)
A_identity

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>